[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.11.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/adharmonics/llog"
