apiVersion: v1
kind: Service
metadata:
  name: face-tome-staging
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 5500
  - name: grpc
    protocol: TCP
    port: 8081
    targetPort: 5501
  selector:
    app: face-tome
    env: staging
