apiVersion: v1
kind: Service
metadata:
  name: face-tome-staging
  namespace: product-staging
  labels:
    app: face-tome-staging
    env: staging
    category: product
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 81
    protocol: TCP
    targetPort: 8081
  selector:
    app: face-tome
    env: staging
    category: product
    component: web
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: face-tome-staging
  namespace: product-staging
spec:
  podSelector:
    matchLabels:
      app: face-tome
      env: staging
      category: product
      component: web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
      - protocol: TCP
        port: 8080
      - protocol: TCP
        port: 8081
  egress:
    - {}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: face-tome-staging
  namespace: product-staging
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app: face-tome
      env: staging
      category: product
      component: web
