apiVersion: v1
kind: Service
metadata:
  name: face-tome
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    env: staging
    app: face-tome
    category: default
  spec:
    type: LoadBalancer
    loadBalancerIP:
    ports:
    - name: http1
      port: 80
      targetPort: 8080
    - name: http2
      port: 81
      targetPort: 8081
    selector:
      app: face-tome
      env: staging
      component: web
      category: default
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: face-tomeav1.yaml

  namespace: default
spec:
  podSelector:
    matchLabels:
      app: face-tome
      env: staging
      component: web
      category: default
    policyTypes:
    - Ingress
    - Egress
    ingress:
    - ports:
      - protocol: TCP
        port: 8080
      - protocol: TCP
        port: 8081
    egress:
    - {}
